### ISSUE TITLE
[Feat] 반려식물 히스토리 구현

### ISSUE THREAD

**Issue by zbqmgldjfh** [gdsc-konkuk/Plantory-Server#15]
## TODO
- [x] 물주기 히스토리 구현
- [x] 분갈이 히스토리 구현
- [x] 조회 쿼리 수정
- [x] 쿼리 테스트 값 검증 수정
