### ISSUE TITLE
[Feat] github 탬플릿, CI 설정

### ISSUE THREAD

**Issue by goldentrash** [gdsc-konkuk/Plantory-Server#27]
### todo

- [x] ISSUE 탬플릿 등록
- [x] PR 탬플릿 등록
- [x] Github action, CI(test) 워크플로 등록
- [x] 코드오너 등록
