### ISSUE TITLE
[Feat]: Record 반환에 추가 내용 제공

### ISSUE THREAD

**Issue by zbqmgldjfh** [gdsc-konkuk/Plantory-Server#38]
# 개요
클라이언트가 추가 요구한 사항들 제공

## Todo
- [x] GET - LookUp Plants 에 '식물 종' 추가   
- [x] GET - LookUp Record에 상의 했던 내용 제공
    - [x] 물 주기 Boolean 
    - [x] 식물의 별명(nickname)
